/**
 * Provider abstraction for outreach email. Each provider sends through the
 * user's own mailbox via OAuth-authorized APIs and can list replies. New
 * providers implement this interface and register in `registry.ts`.
 */
export interface OutgoingEmail {
  from: { email: string; name?: string | null };
  to: string;
  replyTo?: string | null;
  subject: string;
  text: string;
  html: string;
  /** RFC 5322 Message-ID generated by Localy, used for threading and dedupe. */
  messageId: string;
  inReplyTo?: string | null;
  references?: string[];
  /** Provider thread identifier to continue a conversation. */
  providerThreadId?: string | null;
  headers?: Record<string, string>;
}

export interface SendResult {
  providerMessageId: string | null;
  providerThreadId: string | null;
}

export interface InboundMessage {
  providerMessageId: string;
  providerThreadId: string | null;
  messageIdHeader: string | null;
  inReplyTo: string | null;
  references: string[];
  fromEmail: string;
  fromName: string | null;
  toEmail: string | null;
  subject: string;
  text: string;
  receivedAt: Date;
  /** Heuristic: delivery status notification (bounce). */
  isBounce: boolean;
  /** For bounces, the original recipient if it could be determined. */
  bouncedRecipient: string | null;
}

export interface ProviderTokens {
  accessToken: string;
  refreshToken: string | null;
  expiresAt: Date | null;
}

export interface ProviderAccount {
  email: string;
  displayName: string | null;
  providerAccountId: string;
  scopes: string[];
}

export interface ProviderCredentials {
  accessToken: string | null;
  refreshToken: string | null;
  expiresAt: Date | null;
  email: string;
  syncCursor: string | null;
}

export interface SyncResult {
  messages: InboundMessage[];
  nextCursor: string | null;
}

export interface EmailProvider {
  readonly id: 'gmail' | 'microsoft' | 'sandbox';
  readonly label: string;
  readonly scopes: string[];
  /** What the provider can report. Used to label analytics honestly. */
  readonly capabilities: { deliveryConfirmation: boolean; opens: boolean; replies: boolean; bounces: boolean };
  send(creds: ProviderCredentials, email: OutgoingEmail): Promise<SendResult>;
  sync(creds: ProviderCredentials, since: Date): Promise<SyncResult>;
  healthCheck(creds: ProviderCredentials): Promise<{ ok: boolean; message?: string }>;
  refresh?(refreshToken: string): Promise<ProviderTokens>;
}

export class ProviderError extends Error {
  constructor(
    message: string,
    readonly kind: 'auth' | 'rate_limit' | 'transient' | 'permanent' | 'invalid_recipient',
    readonly status: number | null = null,
  ) {
    super(message);
    this.name = 'ProviderError';
  }
}
